module.exports = {
  apps: [
    {
      name: "gbia",
      cwd: "/home/u465383396/apps/gbia",
      script: "server/index.mjs",
      interpreter: "/opt/alt/alt-nodejs22/root/usr/bin/node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 20,
      restart_delay: 2000,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 5000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        PORT: "3008",
        NITRO_HOST: "127.0.0.1",
        NITRO_PORT: "3008",
        VITE_SITE_URL: "https://gbia.com.br",
        SITE_URL: "https://gbia.com.br",
      },
    },
  ],
};
