/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteInstitucionalRouteImport } from './routes/site-institucional'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as GbStudioRouteImport } from './routes/gb-studio'
import { Route as GbSocialRouteImport } from './routes/gb-social'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CardapioDigitalRouteImport } from './routes/cardapio-digital'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInstitucionalRoute = SiteInstitucionalRouteImport.update({
  id: '/site-institucional',
  path: '/site-institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GbStudioRoute = GbStudioRouteImport.update({
  id: '/gb-studio',
  path: '/gb-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const GbSocialRoute = GbSocialRouteImport.update({
  id: '/gb-social',
  path: '/gb-social',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioDigitalRoute = CardapioDigitalRouteImport.update({
  id: '/cardapio-digital',
  path: '/cardapio-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/crm': typeof CrmRoute
  '/ecommerce': typeof EcommerceRoute
  '/gb-social': typeof GbSocialRoute
  '/gb-studio': typeof GbStudioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/site-institucional': typeof SiteInstitucionalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/crm': typeof CrmRoute
  '/ecommerce': typeof EcommerceRoute
  '/gb-social': typeof GbSocialRoute
  '/gb-studio': typeof GbStudioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/site-institucional': typeof SiteInstitucionalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/crm': typeof CrmRoute
  '/ecommerce': typeof EcommerceRoute
  '/gb-social': typeof GbSocialRoute
  '/gb-studio': typeof GbStudioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/site-institucional': typeof SiteInstitucionalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cardapio-digital'
    | '/crm'
    | '/ecommerce'
    | '/gb-social'
    | '/gb-studio'
    | '/politica-de-privacidade'
    | '/site-institucional'
    | '/sitemap.xml'
    | '/termos-de-uso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cardapio-digital'
    | '/crm'
    | '/ecommerce'
    | '/gb-social'
    | '/gb-studio'
    | '/politica-de-privacidade'
    | '/site-institucional'
    | '/sitemap.xml'
    | '/termos-de-uso'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cardapio-digital'
    | '/crm'
    | '/ecommerce'
    | '/gb-social'
    | '/gb-studio'
    | '/politica-de-privacidade'
    | '/site-institucional'
    | '/sitemap.xml'
    | '/termos-de-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CardapioDigitalRoute: typeof CardapioDigitalRoute
  CrmRoute: typeof CrmRoute
  EcommerceRoute: typeof EcommerceRoute
  GbSocialRoute: typeof GbSocialRoute
  GbStudioRoute: typeof GbStudioRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SiteInstitucionalRoute: typeof SiteInstitucionalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-institucional': {
      id: '/site-institucional'
      path: '/site-institucional'
      fullPath: '/site-institucional'
      preLoaderRoute: typeof SiteInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gb-studio': {
      id: '/gb-studio'
      path: '/gb-studio'
      fullPath: '/gb-studio'
      preLoaderRoute: typeof GbStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gb-social': {
      id: '/gb-social'
      path: '/gb-social'
      fullPath: '/gb-social'
      preLoaderRoute: typeof GbSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio-digital': {
      id: '/cardapio-digital'
      path: '/cardapio-digital'
      fullPath: '/cardapio-digital'
      preLoaderRoute: typeof CardapioDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CardapioDigitalRoute: CardapioDigitalRoute,
  CrmRoute: CrmRoute,
  EcommerceRoute: EcommerceRoute,
  GbSocialRoute: GbSocialRoute,
  GbStudioRoute: GbStudioRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SiteInstitucionalRoute: SiteInstitucionalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
