DELETE FROM public.portfolio_items WHERE page_key = 'gb-social';

INSERT INTO public.portfolio_items (page_key, title, description, image_url, link_url, position, visible) VALUES
('gb-social', 'Parmegiana da sexta', 'Post promocional de parmegiana com preço e combo.', '/gb-social-designs/design-01.jpg', '', 0, true),
('gb-social', 'Sextou com sabor', 'Destaque de sexta-feira com prato executivo e refrigerante.', '/gb-social-designs/design-02.jpg', '', 1, true),
('gb-social', 'Seu almoço no centro', 'Banner de buffet com variedade de pratos quentes.', '/gb-social-designs/design-03.jpg', '', 2, true),
('gb-social', 'Variedade no buffet', 'Foto do self-service com opções de carnes e acompanhamentos.', '/gb-social-designs/design-04.jpg', '', 3, true),
('gb-social', 'Almoço no lugar certo', 'Composição de buffet e ambiente aconchegante.', '/gb-social-designs/design-05.jpg', '', 4, true),
('gb-social', 'Segunda mais gostosa', 'Post de segunda-feira com buffet completo.', '/gb-social-designs/design-06.jpg', '', 5, true),
('gb-social', 'Almoço de segunda', 'Pratos quentes em fileiras para segunda-feira.', '/gb-social-designs/design-07.jpg', '', 6, true),
('gb-social', 'Semana começa melhor', 'Destaque de almoço caprichado para começar a semana.', '/gb-social-designs/design-08.jpg', '', 7, true),
('gb-social', 'Variedade de verdade', 'Self-service colorido com saladas e quentes.', '/gb-social-designs/design-09.jpg', '', 8, true),
('gb-social', 'Tempero natural', 'Pratos frescos e naturais do dia a dia.', '/gb-social-designs/design-10.jpg', '', 9, true),
('gb-social', 'Sexta saborosa', 'Post de sexta com refeição completa e suco.', '/gb-social-designs/design-11.jpg', '', 10, true),
('gb-social', 'Lugar agradável', 'Ambiente acolhedor para almoço bem servido.', '/gb-social-designs/design-12.jpg', '', 11, true),
('gb-social', 'Jantar dos namorados', 'Cenário romântico com jantar especial.', '/gb-social-designs/design-13.jpg', '', 12, true),
('gb-social', 'Segunda de combo', 'Combo de frango com refrigerante para dois.', '/gb-social-designs/design-14.jpg', '', 13, true),
('gb-social', 'Combo prático', 'Dois pratos executivos com refrigerante 2L.', '/gb-social-designs/design-15.jpg', '', 14, true),
('gb-social', 'Jantar em família', 'Duas parmegianas com Coca-Cola 2L para dividir.', '/gb-social-designs/design-16.jpg', '', 15, true),
('gb-social', 'Quinta rodada dupla', 'Promoção de cerveja artesanal com chopp.', '/gb-social-designs/design-17.jpg', '', 16, true),
('gb-social', 'Nova semana chegando', 'Post de boas-vindas à semana com carinho.', '/gb-social-designs/design-18.jpg', '', 17, true),
('gb-social', 'Sábado é dia de comer bem', 'Almoço de sábado com variedade e conforto.', '/gb-social-designs/design-19.jpg', '', 18, true),
('gb-social', 'Difícil escolher uma opção', 'Mesa cheia de opções do buffet.', '/gb-social-designs/design-20.jpg', '', 19, true),
('gb-social', 'Sextou caprichado', 'Almoço especial de sexta-feira.', '/gb-social-designs/design-21.jpg', '', 20, true),
('gb-social', 'Vem montar seu prato', 'Convite para montar prato no buffet.', '/gb-social-designs/design-22.jpg', '', 21, true),
('gb-social', 'Já almoçou hoje?', 'Lembrete divertido para o almoço diário.', '/gb-social-designs/design-23.jpg', '', 22, true),
('gb-social', 'Qualidade, variedade e conforto', 'Benefícios do restaurante em um post.', '/gb-social-designs/design-24.jpg', '', 23, true),
('gb-social', 'Seu almoço pode ser assim', 'Prato executivo bem servido do dia.', '/gb-social-designs/design-25.jpg', '', 24, true),
('gb-social', 'Paella à moda', 'Frutos do mar em paella especial.', '/gb-social-designs/design-26.jpg', '', 25, true),
('gb-social', 'Filé de peixe grelhado', 'Peixe grelhado com molho de camarão.', '/gb-social-designs/design-27.jpg', '', 26, true),
('gb-social', 'Moqueca capixaba', 'Moqueca tradicional capixaba da casa.', '/gb-social-designs/design-28.jpg', '', 27, true),
('gb-social', 'Almoço executivo', 'Prato do dia com arroz, feijão e guarnição.', '/gb-social-designs/design-29.jpg', '', 28, true),
('gb-social', 'Menu da semana', 'Composição de pratos da semana.', '/gb-social-designs/design-30.jpg', '', 29, true),
('gb-social', 'Especial da casa', 'Prato especial com destaque para o chef.', '/gb-social-designs/design-31.jpg', '', 30, true);